services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-stomp
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15675:15675"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_web_mqtt tcp_listeners [15675]
    # Enable MQTT and Auth plugins. STOMP removed.
    command: /bin/bash -c "rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_web_mqtt rabbitmq_auth_backend_http rabbitmq_auth_backend_cache && rabbitmq-server"

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway" # Access host ports from container
    depends_on:
      - rabbitmq
