auth_backends.1 = internal
auth_backends.2 = cache

# Configure Cache Backend to use HTTP Backend
auth_cache.cached_backend = http
# Cache TTL in milliseconds (60 seconds)
auth_cache.cache_ttl = 60000

auth_http.http_method   = post
auth_http.user_path     = http://nginx/api/auth/mqtt/user
auth_http.vhost_path    = http://nginx/api/auth/mqtt/vhost
auth_http.resource_path = http://nginx/api/auth/mqtt/resource
auth_http.topic_path    = http://nginx/api/auth/mqtt/topic

# Enforce 3 minute (180 seconds) session/queue expiry
mqtt.max_session_expiry_interval_seconds = 180


